#!/bin/bash
#PBS -P HEAL0790
#PBS -N md3_Hinok
#PBS -l select=1:ncpus=2:ngpus=1
#PBS -l walltime=12:00:00
#PBS -q gpu_1
#PBS -m abe
#PBS -M nithompsona@yahoo.com
#PBS -o /mnt/lustre/users/iajadi/Current_Proj_3/MDM2-MDMX_RING/Recep-Hinok/md_output
#PBS -e /mnt/lustre/users/iajadi/Current_Proj_3/MDM2-MDMX_RING/Recep-Hinok/md_error
#PBS

module purge
module add chpc/amber/18/cuda10.1/openmpi-3.1.0/gcc-6.1.0
source $AMBERHOME/amber.sh

pushd /mnt/lustre/users/iajadi/Current_Proj_3/MDM2-MDMX_RING/Recep-Hinok
exe=$AMBERHOME/bin/pmemd.cuda
$exe -O -i md.in -o md3.out -p com_solvated.top -c md2.rst -r md3.rst -x md3.mdcrd
popd
